window.TTNStrategyData = {
  "belief": {
    "name": "Belief Search",
    "status": "Heuristic",
    "family": "Belief heuristic",
    "playable": true,
    "formula": "Q(I,a) = meanₕ V_oracle(T(h,a))",
    "verdict": "Easy to interpret and often strong, but not protected against strategic exploitation.",
    "overview": "Belief Search lists every full history still compatible with what the player has observed. It applies the same candidate move to every one of those histories, scores the resulting positions with the exact perfect-information oracle, averages the scores, and takes the best mean.",
    "player": "The acting player is assumed to maximize the site's win/draw/loss utility. At the current decision it treats the surviving histories as the relevant uncertainty set and chooses one action for the whole information set.",
    "opponent": "It does not learn or infer a behavioral model of the opponent. After the current move, the continuation value comes from a fully informed minimax oracle, which is stronger information than future legal players actually have.",
    "hidden": "Every distinct compatible history is weighted equally. Equal weight is a modeling choice; it is not a Bayesian posterior induced by the opponent's strategy.",
    "objective": "Choose the action with the largest average perfect-information continuation value across the current information set.",
    "guarantee": "It exactly optimizes that stated one-step average-value objective, provided the information set and oracle values are correct.",
    "notGuarantee": "It has no Nash-equilibrium, minimax-security, no-regret, or exploitability guarantee for the full imperfect-information game.",
    "failure": "Equal weighting can put too much mass on implausible histories. The omniscient continuation can also mis-rank moves because real future players remain partially informed. Its deterministic action choice can be predictable.",
    "cost": "Moderate. For every legal action it evaluates all compatible histories, but the perfect-information continuation is memoized.",
    "best": "Use it when you value interpretability, want an aggressive baseline, or believe the equal-weight possibility model is a reasonable approximation. It can outperform equilibrium play against some weak opponents, but that performance is opponent-dependent.",
    "nash": "Unlike MCCFR, Belief Search optimizes a local surrogate objective rather than long-run counterfactual regret. It may be more exploitative, but it gives up worst-case security."
  },
  "softmax": {
    "name": "Softmax Mixed",
    "status": "Heuristic mixed",
    "family": "Randomized heuristic",
    "playable": true,
    "formula": "σ(a|I) ∝ exp(β Q(I,a)), β = 2.2",
    "verdict": "A useful noisy opponent model; randomness alone does not make it game-theoretic mixing.",
    "overview": "Softmax Mixed starts with the same Belief Search scores, then turns those scores into a probability distribution. Higher-value moves are exponentially more likely, while lower-value legal moves still receive positive probability.",
    "player": "The player is modeled as bounded-rational rather than a strict optimizer. The temperature parameter controls how sharply choice probability responds to estimated move quality.",
    "opponent": "No opponent strategy is learned. If the opponent knows the score-to-probability rule, the resulting fixed stochastic behavior may still be exploitable.",
    "hidden": "It inherits Belief Search's equal-weight compatible-history model and its perfect-information continuation oracle.",
    "objective": "Produce a smooth randomized policy whose probability mass increases with the heuristic quality score.",
    "guarantee": "The policy is a valid normalized full-support behavioral distribution over legal actions.",
    "notGuarantee": "There is no Nash, minimax, regret, or payoff-optimality guarantee. Softmax probabilities need not resemble equilibrium probabilities.",
    "failure": "A strategically necessary equilibrium mix can put probability on actions for reasons unrelated to their standalone heuristic score. Softmax can therefore randomize in exactly the wrong proportions.",
    "cost": "Moderate. Nearly all computation is the Belief Search scoring; exponentiation, normalization, and sampling are negligible.",
    "best": "Use it when you want stochastic, human-like, or bounded-rational play; when testing robustness to decision noise; or when you want mixing without equilibrium training.",
    "nash": "Both Softmax and MCCFR output behavioral probabilities. The difference is why: Softmax transforms move scores, while MCCFR probabilities arise from regret minimization against strategic counterplay."
  },
  "extensive": {
    "name": "Extensive CFR (modal)",
    "status": "Deterministic projection",
    "family": "Extensive-form interpretation",
    "playable": true,
    "formula": "a* = arg maxₐ σ̄_MCCFR(a|I)",
    "verdict": "Good for seeing what the equilibrium learner favors; weaker than actually sampling its policy.",
    "overview": "This strategy uses the same extensive-form information-set key and the same trained MCCFR average policy as Equilibrium Mixed, but then discards the distribution and always chooses the highest-probability action.",
    "player": "The player trusts the extensive-form self-play solution but requires a deterministic move at each information set.",
    "opponent": "The source policy was trained against strategic self-play. Once the randomization is removed, however, an adapting opponent may exploit the now-predictable choice.",
    "hidden": "The policy is indexed directly by the player's observation history. It does not average a hand-built list of hidden worlds at decision time.",
    "objective": "Select the modal action of the learned average MCCFR behavioral strategy.",
    "guarantee": "It faithfully reports the most probable action under the learned MCCFR average policy.",
    "notGuarantee": "It does not inherit the Nash/minimax guarantee of the mixed policy. Even the mode of an exact equilibrium can be exploitable if equilibrium requires randomization.",
    "failure": "The main failure mode is destroying strategically essential mixing. A 55%/45% equilibrium split can become 100%/0%, which changes the game faced by the opponent.",
    "cost": "High training cost inherited from MCCFR, followed by an almost free table lookup at play time.",
    "best": "Use it for interpretation, demos, or when you need a deterministic representative of the learned extensive-form policy. Do not use it when equilibrium security is the goal.",
    "nash": "It is derived from the Nash-target policy but is not itself the Nash-target policy. The distinction is exactly the lost randomization."
  },
  "nash": {
    "name": "Equilibrium Mixed (MCCFR)",
    "status": "Equilibrium target",
    "family": "Regret-minimizing behavioral strategy",
    "playable": true,
    "formula": "a ~ σ̄_MCCFR(·|I)",
    "verdict": "The strongest legal theoretical default when the opponent is unknown or strategic.",
    "overview": "Equilibrium Mixed trains both players with outcome-sampling Monte Carlo Counterfactual Regret Minimization. At play time it samples from the time-averaged behavioral strategy at the player's current information set. The probabilities are strategic: they are shaped by counterfactual regret accumulated under self-play.",
    "player": "Players maximize expected zero-sum utility, remember their own actions and observations, and can condition only on information available at their information sets. The game must be finite and have perfect recall for the standard convergence result used here.",
    "opponent": "Training assumes strategic self-play, but the minimax security interpretation is stronger: at exact equilibrium the player's guaranteed value does not require the eventual opponent to also play equilibrium.",
    "hidden": "There is no manually imposed equal-weight hidden-state distribution in the policy. Reach probabilities are generated endogenously by the players' behavioral strategies through the extensive-form tree.",
    "objective": "Drive counterfactual regret toward zero at each information set and use the average strategy. In two-player zero-sum games, vanishing regret drives average play toward the Nash/minimax set.",
    "guarantee": "For finite two-player zero-sum perfect-recall extensive-form games, CFR/MCCFR are no-regret methods and the average strategy converges toward Nash/minimax equilibrium as training grows.",
    "notGuarantee": "The browser's finite training run is not an exact Nash certificate. The site currently does not compute an exact exploitability bound for the deployed policy, so residual error is possible.",
    "failure": "Finite Monte Carlo training creates variance and residual regret. Also, minimax-secure play is not designed to maximize exploitation of a known weak opponent; a targeted strategy can earn more against that particular opponent.",
    "cost": "Highest up-front cost. Outcome sampling avoids full-tree enumeration, and sparse tables, bitmasks, memoization, and lazy training keep it practical. Once trained, action selection is a cheap lookup and sample.",
    "best": "If 'best' means hardest to exploit or best worst-case guarantee against an unknown strategic opponent, this is the site's preferred legal strategy. More training generally improves the equilibrium approximation.",
    "nash": "This is the Nash-target strategy itself. In a fully solved version of the game, its average behavioral policy is the object that carries the minimax security guarantee."
  },
  "robust": {
    "name": "Robust Maximin",
    "status": "Robust heuristic",
    "family": "Ambiguity-averse decision rule",
    "playable": true,
    "formula": "a* = arg maxₐ minₕ V_oracle(T(h,a))",
    "verdict": "Best for worst-hidden-state protection, but that is not the same as minimaxing the opponent.",
    "overview": "Robust Maximin refuses to assign probabilities to the hidden histories that remain possible. For every move it asks for the worst continuation among those compatible histories, then chooses the move with the strongest floor.",
    "player": "The player is ambiguity-averse. Avoiding the worst compatible hidden state is more important than maximizing average value.",
    "opponent": "The adversarial object in the formula is the hidden history, not the opponent's complete behavioral strategy. Continuation is still evaluated with a fully informed minimax oracle.",
    "hidden": "No probabilities are assigned to compatible histories. Any surviving history may be the one that determines the decision.",
    "objective": "Maximize the minimum perfect-information continuation value over the current compatible-history set.",
    "guarantee": "It exactly optimizes this current-action robust objective.",
    "notGuarantee": "It is not the game-theoretic minimax strategy for the imperfect-information game and does not guarantee the extensive-form game value.",
    "failure": "A technically possible but extremely implausible history can dominate the decision, causing excessive conservatism. It also inherits the omniscient-continuation approximation.",
    "cost": "Moderate and close to Belief Search. It evaluates all action/history combinations but aggregates by minimum instead of mean.",
    "best": "Use it when you intentionally distrust probability assignments and want protection against the worst hidden state currently consistent with your observations.",
    "nash": "Robust Maximin protects against state ambiguity at one decision. Nash/minimax protects against strategic opponent policies over the entire game. They solve different adversarial problems."
  },
  "thompson": {
    "name": "Thompson World Sampling",
    "status": "Posterior-style heuristic",
    "family": "Probability matching",
    "playable": true,
    "formula": "h ~ Uniform(I), a* = arg maxₐ V_oracle(T(h,a))",
    "verdict": "A natural exploration baseline, but only Bayesian if the world distribution is actually a posterior.",
    "overview": "Thompson World Sampling samples one compatible hidden history and then acts as if that sampled history were true, choosing the oracle-best action for it. Different samples naturally create randomized behavior.",
    "player": "The player uses probability matching: uncertainty over the world is converted into randomization over actions through sampled scenarios.",
    "opponent": "No behavioral opponent model is inferred. Once a history is sampled, the continuation oracle assumes fully informed optimal play.",
    "hidden": "The current implementation samples uniformly from compatible histories. That is a possibility model, not automatically a Bayesian posterior.",
    "objective": "Sample a plausible hidden world, then choose the action that is optimal in that sampled world.",
    "guarantee": "It correctly implements probability matching for the chosen uniform world distribution.",
    "notGuarantee": "It has no Nash/minimax guarantee. It also has no Bayesian-optimality guarantee unless the uniform distribution really is the correct posterior generated by a justified prior and likelihood.",
    "failure": "A single sampled history may be unrepresentative, producing high-variance choices. A strategic opponent can also exploit the induced action frequencies.",
    "cost": "Usually lighter than full belief aggregation because a single sampled world drives the decision; oracle continuation remains memoized.",
    "best": "Use it as a probability-matching/exploration baseline or to contrast scenario sampling with mean-value and equilibrium approaches.",
    "nash": "Thompson randomizes because the world is uncertain. MCCFR randomizes because strategic unpredictability may be necessary even when the game model is fully specified."
  },
  "random": {
    "name": "Uniform Random",
    "status": "Baseline",
    "family": "Control strategy",
    "playable": true,
    "formula": "σ(a|I) = 1 / |A(I)|",
    "verdict": "A scientific control, not a serious candidate for optimal play.",
    "overview": "Uniform Random deliberately ignores move quality. Every legal action receives the same probability, making it a clean baseline for quantifying how much the other strategies add.",
    "player": "No rationality model beyond selecting a legal action.",
    "opponent": "None.",
    "hidden": "No hidden-state model is used beyond the information needed to identify legal actions.",
    "objective": "Sample uniformly from the legal action set.",
    "guarantee": "Every legal action receives equal positive probability.",
    "notGuarantee": "There is no performance, robustness, regret, equilibrium, or optimality guarantee.",
    "failure": "It throws away nearly all strategically relevant information and is generally easy to outperform.",
    "cost": "Minimal: enumerate the legal actions and sample one.",
    "best": "Use it as a control group in simulations and experiments.",
    "nash": "Randomness is not equivalent to equilibrium. Nash mixing uses very specific probabilities that make strategic deviations unattractive; uniform random generally does not."
  },
  "oracle": {
    "name": "Omniscient Oracle",
    "status": "Illegal benchmark",
    "family": "Perfect-information benchmark",
    "playable": false,
    "formula": "a* = arg maxₐ V_oracle(s,a)",
    "verdict": "The strongest information benchmark—and therefore disqualified from legal play.",
    "overview": "The Omniscient Oracle sees the true hidden board and solves the resulting perfect-information state by exact minimax under the same physical move rules. It is included only to show what hidden information is worth.",
    "player": "A hypothetical fully informed player who sees the actual underlying state.",
    "opponent": "The minimax continuation assumes a fully informed optimal opponent as well.",
    "hidden": "There is no uncertainty. The true state is directly observed.",
    "objective": "Choose the exact perfect-information minimax action in the true state.",
    "guarantee": "It is exact for the perfect-information relaxation implemented by the oracle.",
    "notGuarantee": "Because it violates the legal information structure, it cannot be used to decide which legal strategy is theoretically best.",
    "failure": "Its principal 'failure' is conceptual: it cheats. Comparing its raw win rate to legal strategies mixes decision quality with an information advantage.",
    "cost": "Potentially expensive when solving a new state, then cheap because exact minimax values are memoized.",
    "best": "Use it only as a simulation upper benchmark and to quantify the value of information.",
    "nash": "The Oracle solves a different game: one in which hidden information has been removed. Nash MCCFR solves the actual imperfect-information game."
  }
};
