window.TTNStrategyData = {
  "belief": {
    "name": "Belief-State Search",
    "status": "Information-safe heuristic",
    "family": "Belief-state rollout",
    "playable": true,
    "formula": "Q(I,a) ≈ |I|⁻¹ Σₕ E_{σ̄_R}[u_i | h,a]",
    "verdict": "A stronger belief heuristic: it never hands future play the hidden board.",
    "overview": "Belief-State Search evaluates the same candidate action in every full history currently compatible with the acting player's observations. The important change is the continuation: instead of switching to an omniscient perfect-information minimax oracle after one move, hypothetical games continue with the learned legal regret behavioral policy. Future actions are therefore selected from the future acting player's own information set. Every currently compatible history is included; repeated behavioral rollouts estimate the continuation value.",
    "player": "The acting player maximizes expected win/draw/loss utility under an equal-weight set of currently compatible histories. One action must be legal and identical across the whole information set.",
    "opponent": "Future opponent behavior is modeled by the learned regret behavioral policy, not by an omniscient opponent. This makes the continuation information-legal but also makes the evaluation conditional on that reference policy.",
    "hidden": "The hypothetical state retains both players' observation histories. When a mystery action occurs, the physical state and private observations evolve normally; subsequent policy lookups use only the acting player's observation history. The search never exposes the true hidden board merely because it is evaluating a hypothetical world.",
    "objective": "Choose the action with the largest average estimated terminal utility across all histories in the current information set, using information-legal behavioral continuation.",
    "guarantee": "The current information set is enumerated exactly and the same action is enforced across indistinguishable histories. As the number of rollout samples grows, the Monte Carlo estimate converges to the value of the stated regret-policy continuation model.",
    "notGuarantee": "It is not a Nash equilibrium, an exact best response, or a Bayesian-optimal policy. Equal weighting of current compatible histories is still a modeling assumption, and finite rollouts add sampling error.",
    "failure": "If equal-weight current histories are badly calibrated, or if the actual opponent behaves very differently from the regret-policy continuation used for evaluation, the chosen action can be mis-ranked. It is also more computationally expensive than the old one-step oracle heuristic.",
    "cost": "Moderate to high at decision time. Every compatible current history is retained, and the rollout budget is spread across all of them. The continuation is bounded so the browser does not attempt a full extensive-form re-solve at every move.",
    "best": "Use it when you want an interpretable belief-based decision rule without future information leakage. It is deliberately an exploitative/model-based heuristic rather than the equilibrium-security strategy.",
    "nash": "Belief-State Search asks which current action scores best under a chosen belief and continuation model. Regret-Matched Behavioral play instead learns a full information-set policy by counterfactual regret minimization and is the strategy with the equilibrium convergence result."
  },
  "nash": {
    "name": "Regret-Matched Behavioral (MCCFR)",
    "status": "Equilibrium target",
    "family": "Regret-minimizing behavioral strategy",
    "playable": true,
    "formula": "a ~ σ̄_MCCFR(·|I)",
    "verdict": "The strongest legal theoretical default against an unknown strategic opponent.",
    "overview": "This is the site's equilibrium-seeking policy. Both players train by outcome-sampling Monte Carlo Counterfactual Regret Minimization. At play time the agent samples directly from the time-averaged behavioral strategy at its current information set. This is already a genuine behavioral strategy: the fact that training samples terminal histories does not turn the deployed policy into a heuristic random policy.",
    "player": "Players maximize expected zero-sum utility, remember their own actions and observations, and condition only on information available at their information sets. The game is finite and modeled with perfect recall.",
    "opponent": "Training uses strategic self-play. The equilibrium interpretation is minimax: at exact equilibrium, the guaranteed game value does not require the eventual opponent to also play equilibrium.",
    "hidden": "There is no manually imposed equal-weight distribution over hidden worlds. Reach probabilities arise endogenously from the players' behavioral policies through the extensive-form tree.",
    "objective": "Drive counterfactual regret toward zero at every information set and use the average behavioral policy. In a finite two-player zero-sum perfect-recall game, vanishing regret drives average play toward the Nash/minimax set.",
    "guarantee": "Outcome-sampling MCCFR is a no-regret method with the standard asymptotic equilibrium guarantee for finite two-player zero-sum perfect-recall extensive-form games, provided the sampling conditions hold. The average policy is the object with that guarantee.",
    "notGuarantee": "A finite browser training run is not an exact Nash certificate, and the site does not currently compute exact exploitability of the deployed table. More iterations reduce approximation error but do not make a finite run literally exact.",
    "failure": "Finite Monte Carlo training has variance and residual regret. Minimax-secure play also need not maximize payoff against one known weak opponent; an exploitative strategy can score better in that specific matchup.",
    "cost": "Highest up-front training cost among the legal strategies, but outcome sampling keeps each iteration cheap. Once trained, play is a table lookup followed by one behavioral sample.",
    "best": "Use it when 'best' means hardest to exploit, strongest worst-case theory, or the cleanest game-theoretic default against an unknown strategic opponent.",
    "nash": "This is the Nash-target strategy. A normal-form mixed strategy would randomize over enormous complete contingency plans; perfect recall allows the equivalent behavioral representation σ(a|I), which is what is stored and sampled here."
  },
  "robust": {
    "name": "Worst-Case Assumption",
    "status": "Worst-case heuristic",
    "family": "Ambiguity-averse decision rule",
    "playable": true,
    "formula": "a* = arg maxₐ minₕ V_oracle(T(h,a))",
    "verdict": "Protects against the worst currently compatible hidden history, not the worst opponent strategy.",
    "overview": "Worst-Case Assumption refuses to assign probabilities to the hidden histories that remain possible. For every legal move it evaluates the continuation in every compatible history, takes the worst value, and chooses the move with the strongest floor.",
    "player": "The player is ambiguity-averse: protection from the worst compatible hidden state is prioritized over average performance.",
    "opponent": "The adversarial object is the hidden history, not the opponent's complete behavioral strategy. Continuation is still evaluated with the perfect-information oracle, so this is a robust hidden-state heuristic rather than extensive-form minimax.",
    "hidden": "No probabilities are assigned. Any compatible history is allowed to determine the current decision.",
    "objective": "Maximize the minimum perfect-information continuation value over the current compatible-history set.",
    "guarantee": "It exactly optimizes this stated current-action worst-hidden-state objective.",
    "notGuarantee": "It does not guarantee the minimax value of the imperfect-information game and is not a Nash strategy.",
    "failure": "A possible but extremely implausible history can dominate the choice. It can therefore be overly conservative, and the perfect-information continuation is still an optimistic information model for future play.",
    "cost": "Moderate. It evaluates all current action/history combinations and aggregates by the minimum.",
    "best": "Use it when you intentionally do not trust a probability model and want a conservative action against hidden-state ambiguity.",
    "nash": "Worst-Case Assumption protects against uncertainty over the current hidden state. Regret-Matched Behavioral play protects against strategic opponent policies over the entire extensive-form game."
  },
  "thompson_uniform": {
    "name": "Uniform Thompson Sampling",
    "status": "Uniform world sampling",
    "family": "Probability matching baseline",
    "playable": true,
    "formula": "h ~ Uniform(I),  a* = arg maxₐ V_oracle(T(h,a))",
    "verdict": "The clean Thompson-style baseline: every currently compatible hidden history is sampled with equal probability.",
    "overview": "Uniform Thompson Sampling chooses one full history uniformly from the acting player's current compatible-history set and then behaves as if that sampled history were the true world. It chooses the perfect-information oracle-best current action in that sampled world. Randomization comes entirely from uncertainty over which compatible history is selected.",
    "player": "The player uses probability matching over an explicitly uniform possibility model: all currently compatible histories are treated as equally plausible before one is sampled.",
    "opponent": "No opponent behavioral model is inferred when assigning history probabilities. After a world is sampled, the current move is chosen using the perfect-information oracle.",
    "hidden": "Each compatible history receives probability 1/|I|. This is a deliberate baseline assumption, not a Bayesian posterior unless the compatible histories truly are equally likely under a justified generative model.",
    "objective": "Sample one compatible hidden history uniformly and choose the action that is oracle-optimal in that sampled history.",
    "guarantee": "It exactly implements probability matching for the stated uniform distribution over the current compatible-history set.",
    "notGuarantee": "It has no Nash/minimax guarantee and no general Bayesian-optimality guarantee. Equal probability can badly misrepresent histories that a strategic opponent would make much more or less likely.",
    "failure": "The uniform assumption can overweight strategically implausible histories, and a single sampled history produces high-variance actions. The oracle-best current move also assumes the sampled world is known for that decision.",
    "cost": "Low to moderate. Sampling the world is cheap, and only the sampled history is evaluated with the memoized perfect-information oracle.",
    "best": "Use it as the clean control for Thompson-style world sampling. Comparing it directly with Regret-Weighted Thompson isolates the value of replacing equal history weights with strategic reach weights.",
    "nash": "Uniform Thompson randomizes because it is uncertain which hidden history is true. Regret-Matched Behavioral randomizes because strategic unpredictability at an information set may be required for equilibrium."
  },
  "thompson": {
    "name": "Regret-Weighted Thompson Sampling",
    "status": "Policy-weighted sampling",
    "family": "Probability matching",
    "playable": true,
    "formula": "h ~ P_{σ̄_R}(h|I),  a* = arg maxₐ V_oracle(T(h,a))",
    "verdict": "A more strategically informed Thompson variant because compatible histories are weighted by a reference behavioral policy rather than uniformly.",
    "overview": "This strategy samples one compatible full history and then acts as if that sampled history were true. Each compatible history is weighted by its reach probability under the learned average regret behavioral policy, conditioned on the acting player's current information set. The sampled world is then solved with the perfect-information oracle for the current action.",
    "player": "The player performs probability matching over hidden histories and then chooses the action that is best in the sampled history.",
    "opponent": "The posterior-style weights assume past actions were generated by the learned regret behavioral policy. If the real opponent follows a different policy, these weights can be miscalibrated.",
    "hidden": "Compatible histories do not receive equal mass by default. Histories that the reference behavioral policy would make more likely receive more weight; zero-reach histories receive zero weight unless all reference weights collapse, in which case the implementation falls back to uniform sampling.",
    "objective": "Sample a hidden history from a policy-induced conditional distribution, then choose the oracle-best current action for that sampled history.",
    "guarantee": "The history sampler implements probability matching for the distribution induced by the learned regret-policy reach weights over the current compatible-history set.",
    "notGuarantee": "It is not Nash/minimax and is only Bayesian in the conditional sense that the chosen regret policy is accepted as the generative model of past behavior. The perfect-information action after sampling is a Thompson-style heuristic, not an equilibrium continuation.",
    "failure": "If the reference regret policy is poorly trained or the opponent behaves differently, the induced history weights can be wrong. Sampling a single history also creates variance.",
    "cost": "Moderate. It replays compatible histories to compute their regret-policy reach weights, samples one, then uses the memoized oracle for that sampled state.",
    "best": "Use it to test whether a strategic reach model improves Thompson-style scenario sampling relative to the uniform Thompson baseline.",
    "nash": "Regret-Weighted Thompson uses the regret policy only to infer which hidden history is plausible; it then commits to one sampled world. Regret-Matched Behavioral play instead randomizes strategically at the actual information set and retains the equilibrium target."
  },
  "random": {
    "name": "Uniform Random",
    "status": "Baseline",
    "family": "Control strategy",
    "playable": true,
    "formula": "σ(a|I) = 1 / |A(I)|",
    "verdict": "A scientific control, not a candidate for optimal play.",
    "overview": "Uniform Random ignores move quality and gives every legal action the same probability. Its purpose is to measure how much value the informed strategies add.",
    "player": "No rationality model beyond choosing a legal action.",
    "opponent": "None.",
    "hidden": "No hidden-state probability model is used beyond the information needed to determine the legal action set.",
    "objective": "Sample uniformly from legal actions.",
    "guarantee": "Every legal action receives equal positive probability.",
    "notGuarantee": "There is no payoff, robustness, regret, equilibrium, or optimality guarantee.",
    "failure": "It deliberately discards strategically useful information and is generally easy to outperform.",
    "cost": "Minimal.",
    "best": "Use it as the control group in simulations.",
    "nash": "Randomness alone is not equilibrium mixing. Equilibrium probabilities are determined by strategic regret/indifference conditions; uniform randomization generally is not."
  },
  "oracle": {
    "name": "Omniscient Oracle",
    "status": "Illegal benchmark",
    "family": "Perfect-information benchmark",
    "playable": false,
    "formula": "a* = arg maxₐ V_oracle(s,a)",
    "verdict": "The strongest information benchmark—and therefore disqualified from legal play.",
    "overview": "The Omniscient Oracle sees the true hidden board and solves the resulting perfect-information state by exact minimax under the same physical move rules. It exists only to quantify the value of information.",
    "player": "A hypothetical fully informed player.",
    "opponent": "The continuation assumes a fully informed optimal opponent as well.",
    "hidden": "There is no uncertainty because the true state is directly observed.",
    "objective": "Choose the exact perfect-information minimax action in the true state.",
    "guarantee": "Exact for the implemented perfect-information relaxation.",
    "notGuarantee": "It cannot establish which legal imperfect-information strategy is best because it violates the game's information constraints.",
    "failure": "Its conceptual limitation is that it cheats. Raw win-rate comparisons mix strategy quality with an information advantage.",
    "cost": "Potentially expensive the first time a state is solved, then cheap through memoization.",
    "best": "Use it only as a simulation benchmark and information-value upper reference.",
    "nash": "The Oracle solves a different game in which hidden information is removed. Regret-Matched Behavioral MCCFR solves the actual imperfect-information game."
  }
};
